require: rubocop-rails
Style/Documentation:
  Enabled: false
Rails/InverseOf:
  Enabled: false

AllCops:
  Exclude:
    - config/environments/**
    - tmp/**/*
    - storage/**/*
    - node_modules/**/*
    - bin/**
    - db/schema.rb
    - spec/database_cleaner.rb
    - spec/capybara_rspec.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/initializers/content_security_policy.rb
    - lib/tasks/auto_annotate_models.rake
    - db/seeds.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - db/migrate/*

Lint/MissingSuper:
  Enabled: false