development: &development
  adapter: redis
  url: redis://redis:6379/1

test:
  <<: *development

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: my_app_production
