name: App tests
on:
  pull_request:

jobs:
  app-tests:
    uses: owen2345/reusable-ci-cd-actions/.github/workflows/tests.yml@main
    with:
      prepare_db_cmd: 'yarn install && bundle exec rails db:setup'
      rspec_cmd: 'bundle exec rspec'
      run_rubocop: true
      eslint_cmd: 'yarn eslint'
      min_coverage: 95

